### ISSUE TITLE
把demo中appkey改为自己的appkey，回调不到app了

### ISSUE THREAD

**Issue by immoose** [mobileresearch/weibo_ios_sdk_sso-oauth#23]
文档中的bundle id也不知道有什么用

**Comment by mobileresearch** [comment]
请认真看说明文档，还有需要注册你应用的appkey，bundle id

**Comment by immoose** [comment]
谢谢。
我在开放平台注册appkey的时候只注册获得了appkey，没有像文档中所写的"向开放平台注册应用程序的bundle id"的操作。
我把demo中.pch和url schema的appkey改成我的appkey，回调app时候就进入了sina.com

**Comment by xujialiang** [comment]
根本就不让注册appkey 和bundle id好吗？不知道啥时候能用
