### ISSUE TITLE
ios dev 6.1 sdk ，so many warning 

### ISSUE THREAD

**Issue by ghost** [mobileresearch/weibo_ios_sdk_sso-oauth#25]
,,,not undersnd why u use object->isa ,, 

if u want to check your own class , why not try like this,

base : NSObject 
{
     int type; //  class type
} 

xxx1 : base
{
 JKArray array;
  xxxx xx;
}
“-” jk_encode_add_atom_to_buffer:( xxx ) xxx;

and not use case JKClassString: case JKClassNumber:,goto。。
 just like "PO" try to use "OO",

**Comment by refox0** [comment]
or ,, use NSJSONSerialization relace jsonkit ,
looks battler.
