### ISSUE TITLE
为何新版新浪微博 SDK 改为闭源了？

### ISSUE THREAD

**Issue by clowwindy** [mobileresearch/weibo_ios_sdk_sso-oauth#27]
新浪微博提供的接口只是 API，为何 SDK 也要闭源？

这样不能帮你们改 bug 了，包括一些很低级的 bug。比如 handleOpenURL 只返回 YES，导致只能把新浪微博放在 handleOpenURL 的最后一个 else 里。否则后面的第三方 App 都拿不到 URL 请求了。

说实话很多 SDK 做的很烂，比如 Evernote 大家都公认它是一坨屎，但因为它是开源的，有 bug 也能查，界面丑也可以改，所以能忍。新浪微博的新版 SDK 如果闭源了，我们以后不会再用，宁可从旧版上 fork 一个出来。

**Comment by ayanamist** [comment]
反正是标准的OAuth 2.0吧，随便找个OAuth 2.0的库自己封装下就可以吧，干嘛要用这个鸡肋货

**Comment by clowwindy** [comment]
@ayanamist 其实就用到了能它显示个登录界面和跳转新浪微博 App 再跳回来的功能，别的 API 调用反正都是自己发 HTTP 请求。

另外那个登录界面上有些文字是放在 strings 文件里的，有些是在代码里写死的。闭源后还不能改了。

**Comment by ayanamist** [comment]
@clowwindy 找个Facebook的SDK改改咧，生成登录页面URL和接受跳转回来token的代码也是OAuth 2.0标准呀

**Comment by clowwindy** [comment]
Any response here?

**Comment by Tinghui** [comment]
这个SDK让人已经无力吐槽......。最后可能只会用它来调新浪微博的客户端，开网页授权和其他的一些API调用全部都要自己封一套HTTP请求。

**Comment by agassiyzh** [comment]
我目前还在用cocoapods中我上传的0.0.1是开源的版本
