### ISSUE TITLE
文档中所谓“Bundle id：向开放平台注册应用程序的 bundle id。” 到底啥意思？要怎么做？

### ISSUE THREAD

**Issue by doneykoo** [mobileresearch/weibo_ios_sdk_sso-oauth#28]
文档中，
**“3. 定义所需常量” **部分，
有一条：**“Bundle id：向开放平台注册应用程序的 bundle id。” **
到底啥意思？ 其实跟代码无关嘛？
要怎么做？

**Comment by mobileresearch** [comment]
http://open.weibo.com/wiki/%E7%A7%BB%E5%8A%A8%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8E%A5%E5%85%A5

请参见此页面
4、在“我的应用 - 应用信息”填写应用的平台信息

谢谢

**Comment by longzihang** [comment]
Bundle id 是否 app 在苹果appstore的Bundle id。

**Comment by doneykoo** [comment]
@mobileresearch 谢谢，我再试试。
