### ISSUE TITLE
demo 都不正常，能再牛逼一些嘛

### ISSUE THREAD

**Issue by longzihang** [mobileresearch/weibo_ios_sdk_sso-oauth#29]

**Comment by mobileresearch** [comment]
请问出现了什么问题

**Comment by longzihang** [comment]
sso授权不能回调，只能webview登录。

**Comment by longzihang** [comment]
sso授权不能回调，会跳转到redirect url页面

在 2013-7-30，下午4:10，mobileresearch notifications@github.com 写道：

**Comment by doneykoo** [comment]
是和这条同一个问题吧啊？
http://open.weibo.com/qa/index.php?qa=15888&qa_1=ios%E5%B9%B3%E5%8F%B0%E4%B8%8B%EF%BC%8Csso%E6%8E%88%E6%9D%83%E6%88%90%E5%8A%9F%EF%BC%88%E6%97%A0%E8%AE%BA%E6%98%AF%E7%BD%91%E9%A1%B5%E6%96%B9%E5%BC%8F%E5%92%8C%E5%BE%AE%E5%8D%9A%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%96%B9%E5%BC%8F%EF%BC%89%E5%90%8E%EF%BC%8C%E4%B8%8D%E8%83%BD%E8%B7%B3%E8%BD%AC%E5%9B%9E%E5%BA%94%E7%94%A8%E8%80%8C%E6%98%AF%E6%98%BE%E7%A4%BA%E4%BA%86%E6%8E%88%E6%9D%83%E5%9B%9E%E8%B0%83%E9%A1%B5%E7%9A%84%E7%BD%91%E9%A1%B5%E5%86%85%E5%AE%B9

我上周使用这里github最新的v2.1也是同样的问题：总是授权后显示redirect url，却不跳回app内。
试了好几次，把sina开放平台、应用信息设置里的Buddle ID和app里设置一致也还是一样。

暂时我是checkout了老的版本来用。

**Comment by longzihang** [comment]
是的，不过我试过很多个版本了，没有一个版本能回调成功的。

在 2013-7-30，下午5:53，doneykoo notifications@github.com 写道：

**Comment by longzihang** [comment]
你是checkout的哪个版本呢？

在 2013-7-30，下午5:53，doneykoo notifications@github.com 写道：

**Comment by doneykoo** [comment]
@longzihang 我checkout了 b24060e4caa5596a585462525a526f36f63dcd96  （Dec 2012 的）
暂时不知道会不会受 http://open.weibo.com/wiki/V1_To_V2  “V1 To V2 新版接口迁移”的 影响。

**Comment by longzihang** [comment]
谢谢，我一直没有尝试使用V1版接口，不过看官方文档说明是去年就已经关闭了V1接口了啊

2013/7/30 doneykoo notifications@github.com

**Comment by mobileresearch** [comment]
是否设置了 url scheme ?

修改 info.plist 文件 URL types 项为自己的 sso 回调地址: wb[你的应用程序的 Appkey] 例如:wb204543436852

**Comment by paulwang2012** [comment]
url scheme 这个应该有设置正确
在sso后 ，微博客户端点 退出看能不能返回自己的应用就知道了

**Comment by longzihang** [comment]
取消授权可以回去 ，只有授权成功才不回去 

发自我的 iPhone
