### ISSUE TITLE
垃圾玩意！！！！

### ISSUE THREAD

**Issue by 6david9** [mobileresearch/weibo_ios_sdk_sso-oauth#34]
想学苹果的闭源，但是你也学学他们的文档啊。写的什么破玩意，那些借口和可以传的参数都没有交代清楚，还是闭源的。以前一直觉得新浪微博sdk比腾讯好，现在在做第三方登录，和腾讯一对比，新浪微博sdk就是个垃圾。这个简化的sdk完全就不是吸引开发者，而是把开发者往其他平台推！！！！！

**Comment by cookingios** [comment]
不能同意更多
