### ISSUE TITLE
nsarray使用objectForKey

### ISSUE THREAD

**Issue by liuzhitao2000** [mobileresearch/weibo_ios_sdk_sso-oauth#4]
SinaWeiBoRequest.m 162行，不是所有result都是字典啊，有的api会返回数组。比如搜索用户提示或者at提示。

临时打个补丁
        if ([result isKindOfClass:[NSDictionary class]]) {
            error_code = [[result objectForKey:@"error_code"] intValue];
        }

希望早日解决

**Comment by zhangcx** [comment]
liuzhitao2000兄台 good! :+1: 
话说 :元芳,你知道sina啥时候能解决?
