### ISSUE TITLE
选择授权帐号后不是跳回我的app，而是打开urlredirect的网址

### ISSUE THREAD

**Issue by xiaoxiaocainiao** [mobileresearch/weibo_ios_sdk_sso-oauth#41]
点“取消”可以跳回我的app。。。。

**Comment by doneykoo** [comment]
据我所知 应该是你在 管理页面里的bundle id 等设置 与 你在xcode工程里的 不一致 导致的

**Comment by RockerHX** [comment]
你可以用了吗？我设置了一样的也还是不行

**Comment by horstleung** [comment]
plist 填上wb你的appID, 再到基本資料那把bundle id 改成你的xcode 那個
redirect_uri要填上，你的代碼要和它一樣
