### ISSUE TITLE
我在使用2.2.0版的sdk时，使用Oauth2.0的方式，但是授权后显示回调页

### ISSUE THREAD

**Issue by ghost** [mobileresearch/weibo_ios_sdk_sso-oauth#42]
我在使用2.2.0版的sdk时，设备没有安装客户端，自动使用Oauth2.0的方式，但是授权后显示回调页，而不是关闭
我不知道将appsercet 赋值给谁。程序没上线，bundleID和 appleID没填。你们把Oauth2.0认证的方法封装了。我不知道才能返回到didReceiveWeiboResponse方法

**Comment by ghost** [comment]
好吧 我自己来解决。bundleID填上，AppleID随便填。文档多处有错误。请尽快更新吧。

**Comment by RockerHX** [comment]
请问一下bundleID怎么填？

**Comment by ghost** [comment]
基本信息，点编辑。

**Comment by helloqidi** [comment]
请问 bundleID 从哪里获得？

**Comment by RockerHX** [comment]
xcode里那个bundleID eg:com.xxx.xxx那个

shicang1990@gmail.com

发件人： helloqidi
发送时间： 2013-09-10 14:45
收件人： mobileresearch/weibo_ios_sdk_sso-oauth
抄送： shicang1990
主题： Re: [weibo_ios_sdk_sso-oauth] 我在使用2.2.0版的sdk时，使用Oauth2.0的方式，但是授权后显示回调页 (#42)
请问 bundleID 从哪里获得？

**Comment by weimeng54** [comment]
这个确实有点坑爹了。我在想了一晚上我才刚写的Demo哪来的Apple ID
