### ISSUE TITLE
是不是SDK中已包含了AFNetworking的API

### ISSUE THREAD

**Issue by xrksudy** [mobileresearch/weibo_ios_sdk_sso-oauth#44]
我今天将weibo_ios_sdk导入项目，我项目是用pod进行管理依赖的，同时我在pod上配置了AFNetworking.项目编译有错误。

能不能不将AFNetworking的api集成到libWeiboSDK.a中啊？

错误如下：
duplicate symbol _OBJC_IVAR_$_AFQueryStringPair._field in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _OBJC_IVAR_$_AFQueryStringPair._value in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _AFQueryStringFromParametersWithEncoding in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _AFQueryStringPairsFromKeyAndValue in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _AFQueryStringPairsFromDictionary in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _OBJC_IVAR_$_AFHTTPClient._baseURL in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _OBJC_IVAR_$_AFHTTPClient._stringEncoding in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _OBJC_IVAR_$_AFHTTPClient._parameterEncoding in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _OBJC_IVAR_$_AFHTTPClient._registeredHTTPOperationClassNames in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _OBJC_IVAR_$_AFHTTPClient._defaultHeaders in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _OBJC_IVAR_$_AFHTTPClient._defaultCredential in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _OBJC_IVAR_$_AFHTTPClient._operationQueue in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _OBJC_IVAR_$_AFHTTPClient._defaultSSLPinningMode in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _OBJC_IVAR_$_AFHTTPClient._allowsInvalidSSLCertificate in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _OBJC_IVAR_$_AFStreamingMultipartFormData._request in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _OBJC_IVAR_$_AFStreamingMultipartFormData._bodyStream in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _OBJC_IVAR_$_AFStreamingMultipartFormData._stringEncoding in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _OBJC_IVAR_$_AFMultipartBodyStream._streamStatus in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _OBJC_IVAR_$_AFMultipartBodyStream._streamError in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _OBJC_IVAR_$_AFMultipartBodyStream._stringEncoding in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _OBJC_IVAR_$_AFMultipartBodyStream._HTTPBodyParts in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _OBJC_IVAR_$_AFMultipartBodyStream._HTTPBodyPartEnumerator in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _OBJC_IVAR_$_AFMultipartBodyStream._currentHTTPBodyPart in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _OBJC_IVAR_$_AFMultipartBodyStream._inputStream in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _OBJC_IVAR_$_AFMultipartBodyStream._outputStream in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _OBJC_IVAR_$_AFMultipartBodyStream._buffer in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _OBJC_IVAR_$_AFMultipartBodyStream._numberOfBytesInPacket in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _OBJC_IVAR_$_AFMultipartBodyStream._delay in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
duplicate symbol _OBJC_IVAR_$_AFHTTPBodyPart._inputStream in:
    /Users/kevin/Library/Developer/Xcode/DerivedData/SNS-fxyrrwlnlgxhpobdhedjjuxrlefb/Build/Products/Debug-iphoneos/libPods.a(AFHTTPClient.o)
    /Users/kevin/Dropbox/00_PersonalProject/SNS/Vendors/Weibo/libWeiboSDK.a(AFHTTPClient.o)
........

**Comment by xrksudy** [comment]
在pod中将AFNetworking去掉，项目编译就正常了。 我感觉如果你要是依赖AFNetworking，要么就写明下，让开发者自己加入这个类库，要么就完全封装好，加给前缀等，必要API重复。

**Comment by iiiyu** [comment]
支持 既然要开源就完全按照业界做法来。 虽然用了github。 但是都没有人来维护有什么意义。 pr也没有人管。

**Comment by mobileresearch** [comment]
我们已经去掉AFNetworking。多谢支持

**Comment by xrksudy** [comment]
谢谢你们的及时修复。我刚刚拉了新版本，之前的编译问题已经没有了。
