### ISSUE TITLE
希望这个project来一个tag好不

### ISSUE THREAD

**Issue by studentdeng** [mobileresearch/weibo_ios_sdk_sso-oauth#45]
各个版本release的时候，保存一个tag多好。
实在是无法理解这种回滚。。。

本来想写到wiki里面，还是写在这里吧

**Comment by agassiyzh** [comment]
确实应该这样 。提交podspec都不方便

在 2013年9月16日下午10:50，curer notifications@github.com写道：

**Comment by mobileresearch** [comment]
2.3.1版本已经添加tag，以后会在版本升级时添加。
