### ISSUE TITLE
遇到ipad无法调出新浪微博

### ISSUE THREAD

**Issue by rufeng18** [mobileresearch/weibo_ios_sdk_sso-oauth#46]
Demo在iphone手机上可以调用出weibo客户端测试,但是在ipad上,不能调用成功,跳出要安装新浪微博客户端,但是ipad上已是最新安装的客户端。调用 [WeiboSDK isAppboAppInstalled] 返回FALSE, 请问下是否有这个问题

**Comment by rufeng18** [comment]
我找到原因了,ipad装的是HD 版，这sdk 不支持HD的，希望可以支持

**Comment by mobileresearch** [comment]
会推动尽快支持，目前排期较满，请耐心等待 非常感谢。
