### ISSUE TITLE
sdk里授权的网址和网站上的不同

### ISSUE THREAD

**Issue by 6david9** [mobileresearch/weibo_ios_sdk_sso-oauth#5]
可能是授权的问题经常验证页面会跳转转到 “请求页不存在   出错了: 链接http://weibo.cn/comment/无效”

**Comment by mobileresearch** [comment]
是Oauth认证的时候？麻烦具体描述下

**Comment by 6david9** [comment]
kSinaWeiboSDKAPIDomain这个常量现在应该替换为@"https://api.weibo.com/2/"
