### ISSUE TITLE
采用Cocoapods添加的SinaWeiboSDK不是最新版么？

### ISSUE THREAD

**Issue by wzsg** [mobileresearch/weibo_ios_sdk_sso-oauth#50]
采用Cocoapods添加的SinaWeiboSDK不是最新版么？

WTF....

**Comment by wentaozone** [comment]
我这几天才把新浪微博分享做了.没看懂你的意思!

**Comment by wzsg** [comment]
Cocoapods是一款iOS第三方包管理器

**Comment by zvving** [comment]
v2.3 都有了，cocoapods 还是旧版啊。

**Comment by wzsg** [comment]
强烈要求更新cocoapods

**Comment by zvving** [comment]
而且这个版本发布信息必须安装 新浪微博 app 才行……果断弃用，依旧用一个旧版本的 sdk。

偌大的新浪就不能提供个完善点的 sdk……

**Comment by vinceyuan** [comment]
旧版本指哪个版本？在哪里下载？

Sent from my iPhone

"Ming Z." notifications@github.com 於 2013年10月23日 上午10:29 寫道：

而且这个版本发布信息必须安装 新浪微博 app 才行……果断弃用，依旧用一个旧版本的 sdk。

偌大的新浪就不能提供个完善点的 sdk……

—
Reply to this email directly or view it on
GitHubhttps://github.com/mobileresearch/weibo_ios_sdk_sso-oauth/issues/50#issuecomment-26876364
.

**Comment by wzsg** [comment]
新浪的技术太烂

**Comment by agassiyzh** [comment]
cocoapods中的那个spec是我个人在维护的。这也是我一直不把cocoapods中的升级的原因。

—

**Comment by zvving** [comment]
@vinceyuan 目前我用的是这个：http://pan.baidu.com/s/1DtDU4 
支持 sso，应用内发微博

**Comment by lerosua** [comment]
cocoapods上的是旧的，之前写了个本地的spec
$cat SinaWeibo.podspec
Pod::Spec.new do |s|
  s.name         = "SinaWeibo"
  s.version      = "2.3.1"
  s.summary      = "sina weibo sdk of sso and Oauth2.0."
  s.homepage     = "https://github.com/mobileresearch/weibo_ios_sdk_sso-oauth"
  s.license      = 'MIT (example)'
  s.license      = {
    :type => 'Commercial',
    :text => <<-LICENSE
        Commercial license.
        Please get a license from Tencent before use.
    LICENSE
  }
  s.author       = { "mobileresearch" => "email@address.com" }
  s.source       = { :git => "https://github.com/mobileresearch/weibo_ios_sdk_sso-oauth.git", :commit => "e7ada5b1b5a3d598653e48bd7748b349699e7281" }
  s.platform     = :ios
  s.source_files = 'libWeiboSDK/*.{h,m}'
  s.resources = "libWeiboSDK/WeiboSDK.bundle"
  s.vendored_libraries= "libWeiboSDK/libWeiboSDK.a"
end
大家在自己的podfile里加入本地的spec即可，类似
pod 'SinaWeibo', :podspec => '~/Documents/work/L-git/SinaWeibo.podspec'

**Comment by zvving** [comment]
@agassiyzh 感谢你的个人维护！

既然针对这个库，建议 pod 也升最新版吧，不然用到的人都会有疑惑。想用旧版本的人，指定版本号即可。

**Comment by agassiyzh** [comment]
好，那我把新的搞上去。

现在有个问题是这样的：

这个库的作者虽然一直在发更新，2.3.0什么的。但是他们貌似不喜欢打tag。没有tag的版本号只能在0.0.1.

我是fork到自己的repo中呢，还是大家要求官方在发布新版本的时候打上tag

在 2013年10月28日，下午3:13，Ming Z. notifications@github.com 写道：

**Comment by zvving** [comment]
作者大人们，求打 tag 啊啊啊~

@mobileresearch @hongtaozhy @jamessshiyuan

**Comment by agassiyzh** [comment]
问题是，我用到现在cocoapods中的这个挺好的。

你们觉得这个版本有什么问题吗？

在 2013年10月28日，下午3:47，Ming Z. notifications@github.com 写道：

**Comment by studentdeng** [comment]
刚刚写了一个新的分享组件。包含了sina sso 登陆，大家有兴趣可以提提意见
https://github.com/studentdeng/CUShareCenter

**Comment by mobileresearch** [comment]
2.3.1 已经填加tag 以后会在发版本升级时候打tag的，非常感谢反馈

**Comment by agassiyzh** [comment]
好，我这就去更新cocoapods上面的版本
在 2013年11月8日，上午11:13，mobileresearch notifications@github.com 写道：

**Comment by hongtaozhy** [comment]
2.4.0已经增加tag，2.4.0版本重新集成了1.0版本sdk的网络统一请求接口用以支持open api，建议更新至此版本。
在 2013年11月8日，下午3:38，Agassi notifications@github.com 写道：
