### ISSUE TITLE
点击授权以后出现新闻客户端推荐页面

### ISSUE THREAD

**Issue by isbase** [mobileresearch/weibo_ios_sdk_sso-oauth#56]
点击授权以后出现新闻客户端推荐页面，这个怎么取消呢。还是因为什么原因出现的呢

**Comment by mobileresearch** [comment]
设置问题 请核对相应设置 参看
https://github.com/mobileresearch/weibo_ios_sdk_sso-oauth/blob/master/微博IOS平台SDK文档V2.4.0.pdf
