### ISSUE TITLE
不支持Build for arm64

### ISSUE THREAD

**Issue by evianzhow** [mobileresearch/weibo_ios_sdk_sso-oauth#57]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_WBProvideMessageForWeiboResponse", referenced from:
      objc-class-ref in ProvideMessageForWeiboViewController.o
  "_OBJC_CLASS_$_WBImageObject", referenced from:
      objc-class-ref in ProvideMessageForWeiboViewController.o
  "_OBJC_CLASS_$_WBMessageObject", referenced from:
      objc-class-ref in ProvideMessageForWeiboViewController.o
  "_OBJC_CLASS_$_WBAuthorizeRequest", referenced from:
      objc-class-ref in SendMessageToWeiboViewController.o
  "_OBJC_CLASS_$_WBSendMessageToWeiboRequest", referenced from:
      objc-class-ref in SendMessageToWeiboViewController.o
  "_OBJC_CLASS_$_WBSendMessageToWeiboResponse", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_WBWebpageObject", referenced from:
      objc-class-ref in ProvideMessageForWeiboViewController.o
  "_OBJC_CLASS_$_WBAuthorizeResponse", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_WBProvideMessageForWeiboRequest", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_WeiboSDK", referenced from:
      objc-class-ref in AppDelegate.o
      objc-class-ref in SendMessageToWeiboViewController.o
      objc-class-ref in ProvideMessageForWeiboViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mobileresearch** [comment]
2.4版本会单独发一个支持64位的
