### ISSUE TITLE
谁能告诉我用这SB SDK如何获取当前登录者的好友信息？

### ISSUE THREAD

**Issue by yyqqing** [mobileresearch/weibo_ios_sdk_sso-oauth#59]
谁能告诉我用这SB SDK如何获取当前登录者的好友信息？

**Comment by mobileresearch** [comment]
通过sso取到的token  通过调用接口
requestWithAccessToken:url:httpMethod:params:delegate:
去获取
具体url和参数 请查阅平台open api文档

PS 公用网络场所注意文明用词
