### ISSUE TITLE
请问sdk支持ARC吗？

### ISSUE THREAD

**Issue by withshe** [mobileresearch/weibo_ios_sdk_sso-oauth#6]
我新建了一个工程，使用了ARC，把JSONKit、SinaWeibo目录复制进工程，编译时出现很多错误，比如下面这些代码：
[userID release], userID = nil;
[accessToken release], accessToken = nil;
[expirationDate release], expirationDate = nil;
[appKey release], appKey = nil;
[appSecret release], appSecret = nil;
[appRedirectURI release], appRedirectURI = nil;
[ssoCallbackScheme release], ssoCallbackScheme = nil;

错误信息类似：release is unavailable: not available in automatic reference counting mode......

**Comment by withshe** [comment]
呵呵，我找到方法了，打扰

**Comment by kirk-ye** [comment]
我也是一样的问题，是怎样解决的？

**Comment by kirk-ye** [comment]
在build phases -》 compile sources 选择文件后面加  -fno-objc-arc
花了我不少时间。
